site_name: 南方医科大学



theme:
  name: material
  language: zh
  custom_dir: overrides


  palette: 
    
  
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/toggle-switch 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

 
   
   
  features:
    - navigation.tabs 
    - search.highlight 
    - navigation.indexes 
    - navigation.expand 
    - navigation.path
    - navigation.footer


  
copyright: Copyright © 2025 Online SMU All Rights Reserved

extra_javascript:
  - 'https://busuanzi.9420.ltd/js' #busuanzi






nav:


  - 前言: 
    - 前言1.0: 前言\前言1.0.md
    - 前言2.0: 前言\前言2.0.md
  
 
  - 更新及说明:
    - 本站使用说明: 更新及说明/本站使用说明.md
    - 更新日志: 更新及说明/更新日志.md
    - 各版本PDF下载: 更新及说明/各版本PDF下载.md
    - 名词解释: 更新及说明/名词解释.md
    - 免责声明: 更新及说明/免责声明.md
    - 目录: 更新及说明/目录.md

  - 新闻速递:
    - 基孔肯雅热: 新闻速递/基孔肯雅热.md

  - 学前班:
    - 引言: 学前班/引言.md
    - 录取通知书: 学前班/录取通知书.md
    - 防诈骗: 学前班/防诈骗.md
    - 假期宿舍准备: 学前班/假期宿舍准备.md
    - 入学交通攻略: 学前班/入学交通攻略.md
 
  - 顺德校区:
    - 引言: 顺德校区/引言.md
    - 地图及指引: 顺德校区/地图及指引.md
    - 出行及游玩: 顺德校区/出行及游玩.md
    - 宿舍及书院: 
      - 引言: 顺德校区/宿舍及书院/引言.md
    - 生命健康: 
      - AED位置: 顺德校区/生命健康/AED位置.md
      - 校医室: 顺德校区/生命健康/校医室.md
      - 医保: 顺德校区/生命健康/医保.md
      - 心理咨询: 顺德校区/生命健康/心理咨询.md
    - 顺德校区防诈骗: 顺德校区/顺德校区防诈骗.md
    - 生活设施: 
      - 维修: 顺德校区/生活设施/维修.md
      - 指纹锁: 顺德校区/生活设施/指纹锁.md
      - 洗澡: 顺德校区/生活设施/洗澡.md
      - 校园网: 顺德校区/生活设施/校园网.md
      - 水电费: 顺德校区/生活设施/水电费.md
      - 饮水机: 顺德校区/生活设施/饮水机.md
      - 快递: 顺德校区/生活设施/快递.md
      - 打印: 顺德校区/生活设施/打印.md
    - 干饭: 
      - 陶然轩（饭堂）: 顺德校区/干饭/陶然轩（饭堂）.md
      - 外卖: 顺德校区/干饭/外卖.md
    - 功能房: 
      - 引言: 顺德校区/功能房/引言.md
      - 春风健身房: 顺德校区/功能房/春风健身房.md
    - 校内动物: 
      - 校猫: 顺德校区/校内动物/校猫.md
      - 羊岛: 顺德校区/校内动物/羊岛.md
    - 社团: 
      - 引言: 顺德校区/社团/引言.md
    - 军训及计算机英语分班: 顺德校区/军训及计算机英语分班.md
    - 教学楼: 
      - 春华堂: 顺德校区/教学楼/春华堂.md
      - 秋实堂: 顺德校区/教学楼/秋实堂.md
    - 顺德校区图书馆: 顺德校区/顺德校区图书馆.md
    - 隐藏地点: 顺德校区/隐藏地点.md
    - 美图:
      - 引言: 顺德校区/美图/引言.md
 
  - 广州校区:
    - 引言: 广州校区/引言.md
    - 地图及指引: 广州校区/地图及指引.md
    - 出行及游玩: 广州校区/出行及游玩.md
    - 宿舍及书院: 
      - 引言: 广州校区/宿舍及书院/引言.md
    - 生命健康: 广州校区/生命健康.md
    - 广州校区防诈骗: 广州校区/广州校区防诈骗.md
    - 生活设施: 
      - 维修: 广州校区/生活设施/维修.md
      - 快递: 广州校区/生活设施/快递.md
      - 打印: 广州校区/生活设施/打印.md
      - 超市: 广州校区/生活设施/超市.md
    - 干饭:
      - 引言: 广州校区/干饭/引言.md
    - 京溪体育场: 广州校区/京溪体育场.md
 
  - 本科学习:
    - 引言: 本科学习/引言.md
    - 学生手册: 本科学习/学生手册.md
    - 绩点: 本科学习/绩点.md
    - 双及格及留级: 本科学习/双及格及留级.md
    - 综测: 本科学习/综测.md
    - 体测: 本科学习/体测.md
    - 课表及评课: 本科学习/课表及评课.md
    - 免修: 本科学习/免修.md
    - 选修课: 本科学习/选修课.md
    - 本科毕业要求: 
      - 引言: 本科学习/本科毕业要求/引言.md
      - 创新学分: 本科学习/本科毕业要求/创新学分.md
      - 劳动学时: 本科学习/本科毕业要求/劳动学时.md
      - 毕业、学士学位、结业: 本科学习/本科毕业要求/毕业、学士学位、结业肄业.md
    - 转专业: 
      - 引言: 本科学习/转专业/引言.md
      - 政策文件公告: 本科学习/转专业/政策文件公告.md
      - 军训-新生专业调整: 本科学习/转专业/军训-新生专业调整.md


  - 发展:
    - 引言: 发展/引言.md
    - 实习:
      - 1: 发展/实习/1.md
    - 入伍: 
      - 1: 发展/入伍/1.md
    - 交换生: 
      - 1: 发展/交换生/1.md
    - 考研: 
      - 1: 发展/考研/1.md
    - 保研: 
      - 1: 发展/保研/1.md
    - 考公:
      - 1: 发展/考公/1.md

  - 友情链接:
    - 引言: 友情链接/引言.md
    - 官方链接及公众号: 友情链接/官方链接及公众号.md
    - QQ群合集: 友情链接/QQ群合集.md
    - 公众号合集:
      - 通用: 友情链接/公众号合集/通用.md
      - 预防: 友情链接/公众号合集/预防.md
    - 其他高校的手册: 友情链接/其他高校的手册.md

  - 生命健康:
    - 引言: 生命健康/引言.md

  - 课外扩展:
    - 引言: 课外扩展/引言.md
    - 怎样用QQ发邮箱: 课外扩展/怎样用QQ发邮箱.md
    - 如何独立乘坐各类交通工具: 课外扩展/如何独立乘坐各类交通工具.md
   
    
  - 学生天地:
    - 引言: 学生天地/引言.md

  - 投稿、后记及测试区:
    - 引言: 投稿、后记及测试区/引言.md
    - 我要投稿: 投稿、后记及测试区/我要投稿.md
    - 测试区: 
      - 1: 投稿、后记及测试区/测试区/1.md
    - 后记: 投稿、后记及测试区/后记.md

    